package br.projecao.ltpw.model;
// Generated 04/05/2019 17:43:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="Departamento"
    ,catalog="projecao"
)
public class Departamento  implements java.io.Serializable {


     private int idDepartamento;
     private String nome;
     private Set<Curso> cursos = new HashSet<Curso>(0);

    public Departamento() {
    }

	
    public Departamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Departamento(int idDepartamento, String nome, Set<Curso> cursos) {
       this.idDepartamento = idDepartamento;
       this.nome = nome;
       this.cursos = cursos;
    }
   
     @Id 
    @GeneratedValue
    
    @Column(name="idDepartamento", unique=true, nullable=false)
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamento")
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }




}


