package br.projecao.ltpw.model;
// Generated 04/05/2019 17:43:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Genero generated by hbm2java
 */
@Entity
@Table(name="Genero"
    ,catalog="projecao"
)
public class Genero  implements java.io.Serializable {


     private int idGenero;
     private String descricao;


    public Genero() {
    }

	
    public Genero(int idGenero, String descricao) {
        this.idGenero = idGenero;
        this.descricao = descricao;
    }

    @Id   
    @GeneratedValue
    @Column(name="idGenero", unique=true, nullable=false)
    public int getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(int idGenero) {
        this.idGenero = idGenero;
    }

    
    @Column(name="descricao", nullable=false, length=45)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }





}


