package br.projecao.ltpw.model;
// Generated 04/05/2019 17:43:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name="Pessoa"
    ,catalog="projecao"
)
public class Pessoa  implements java.io.Serializable {


     private int idPessoa;
     private Genero genero;
     private String nome;
     private String sobrenome;
     private String matricula;
     private Date dataNascimento;
     private Date dataIngresso;
     private String email;
     private String usuario;
     private String senha;
     private Aluno aluno;
     private Set<Endereco> enderecos = new HashSet<Endereco>(0);
    public Pessoa() {
    }

	
    public Pessoa(int idPessoa, Genero genero) {
        this.idPessoa = idPessoa;
        this.genero = genero;
    }
   
     @Id 
     @GeneratedValue
    @Column(name="idPessoa", unique=true, nullable=false)
    public int getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(int idPessoa) {
        this.idPessoa = idPessoa;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGenero")
    public Genero getGenero() {
        return this.genero;
    }

    @OneToOne(mappedBy = "pessoa")
    @Cascade({CascadeType.ALL})
    public Aluno getAluno() {
        return aluno;
    }

    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    
  
    
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sobrenome", length=45)
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }

    
    @Column(name="matricula", length=45)
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento", length=10)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataIngresso", length=10)
    public Date getDataIngresso() {
        return this.dataIngresso;
    }
    
    public void setDataIngresso(Date dataIngresso) {
        this.dataIngresso = dataIngresso;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="usuario", length=45)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="senha", length=45)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }


@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Pessoa_Endereco", catalog="projecao", joinColumns = { 
        @JoinColumn(name="Pessoa_idPessoa", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Endereco_idEndereco", nullable=false, updatable=false) })
    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set<Endereco> enderecos) {
        this.enderecos = enderecos;
    }




}


